guestbook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create/$', views.create, name='create')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^guestbook/', include('guestbook.urls', namespace="guestbook")),
]

polls/urls.py
from django.conf.urls import url
#from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

guestbook/models.py
import datetime
from django.db import models
from django.utils import timezone


class text(models.Model):
    title_text = models.CharField(max_length=200, blank=True)
    question_text = models.TextField(blank=True)
    pub_date = models.DateTimeField('date published')
    def __str__(self):      # __unicode__ on Python 2
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

guestbook/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from .models import text



def index(request):
    latest_question_list = text.objects.order_by('-pub_date')[:50]
    print (latest_question_list)
    length = []
    for i in latest_question_list:
        length.append(len(i.question_text))

    context = {'latest_question_list': latest_question_list,
        'length': length,
    }
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        q = text(title_text=request.POST['titill'], pub_date=timezone.now(),question_text=request.POST['txtArea'])
        q.save()
    return render(request, 'guestbook/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(text, pk=question_id)
    context = {
        'question': question,
        'previous':int(question_id) - 1,
        'next':int(question_id) + 1,
    }
    return render(request, 'guestbook/detail.html', context)

def create(request):
    # if this is a POST request we need to process the form data



    return render(request, 'guestbook/create.html')











"""
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
"""

polls/views.py
#from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect#, HttpResponse
#from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

print("Flott Verk höhh")

guestbook/templates/guestbook/create.html
{% load staticfiles %}
<html style="overflow-y: scroll;" lang="en">
<link rel="stylesheet" type="text/css" href="{% static 'guestbook/bootstrap.css' %}" />
<title>Swag</title>
<body><br>
<div class="container theme-showcase" role="main">
  <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation"><a href="../">Home</a></li>
          <li role="presentation" class="active"><a href="#">New Post</a></li>
          <li role="presentation"><a href="#">About</a></li>
        </ul>
      </nav>
      <h3 class="text-muted">Guestbook</h3>
    </div>
<form action="/guestbook/" method="post">
    {% csrf_token %}
    {{ form }}
    <br>
    <input type="text" class="form-control"  placeholder="Title" name="titill"/>
    <br>
    ​<textarea name="txtArea" class="form-control" rows="10" cols="70" placeholder="Text" ></textarea>
    <br>
    <input type="submit" value="Submit" class="btn btn-primary"/>
</form>

guestbook/templates/guestbook/detail.html
{% load staticfiles %}
<html style="overflow-y: scroll;" lang="en">
<link rel="stylesheet" type="text/css" href="{% static 'guestbook/bootstrap.css' %}" />
<body><br>
<title>{{ question.title_text }}</title>
<div class="container theme-showcase" role="main">
  <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><a href="../../">Home</a></li>
          <li role="presentation"><a href="../../create/">New Post</a></li>
          <li role="presentation"><a href="#">About</a></li>
        </ul>
      </nav>
      <h3 class="text-muted">Guestbook</h3>
    </div>
      <div class="jumbotron">
          <h2>{{ question.title_text }}</h2>
          <p>{{ question.question_text }}</p>
      </div>
</div>
<nav class="container">
  <ul class="pager">
    <li class="previous"><a href="{% url 'guestbook:detail' previous %}"><span aria-hidden="true">&larr;</span> Older</a></li>
    <li class="next"><a href="{% url 'guestbook:detail' next %}">Newer <span aria-hidden="true">&rarr;</span></a></li>
  </ul>
</nav>

</body>

guestbook/templates/guestbook/index.html
{% load staticfiles %}
<html style="overflow-y: scroll;" lang="en">
<link rel="stylesheet" type="text/css" href="{% static 'guestbook/bootstrap.css' %}" />
<title>Swag changed by Aleksei. [2015]</title>
<body><br>
<div class="container theme-showcase" role="main">
  <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><a href="#">Home</a></li>
          <li role="presentation"><a href="create">New Post</a></li>
          <li role="presentation"><a href="#">About</a></li>
        </ul>
      </nav>
      <h3 class="text-muted">Guestbook</h3>
    </div>
{% if latest_question_list %}
  {% for text in latest_question_list %}
    <div class="list-group">
      <a href="{% url 'guestbook:detail' text.id %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ text.title_text }}</h4>
        <p class="list-group-item-text">{{text.question_text|slice:"200"}}{% if text.question_text|length > 200 %}... {% endif %}</p>
      </a>
    </div>
    {% endfor %}


  <!--<ul>swag123123
    {% for text in latest_question_list %}
        <li><a href="{% url 'guestbook:detail' text.id %}">{{ text.title_text }}</a></li>
    {% endfor %}
  </ul>
-->
  <footer>
      <a href="create">Gera nýtt</a>

  </footer>
{% else %}
    <p>No text are available.</p>
{% endif %}
</div>
</body>

polls/templates/polls/detail.html
{% load staticfiles %}
<html style="overflow-y: scroll;" lang="en">
<link rel="stylesheet" type="text/css" href="{% static 'guestbook/bootstrap.css' %}" />
<body><br>
<title>{{ question.title_text }}</title>
<div class="container theme-showcase" role="main">
  <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><a href="../../">Home</a></li>
          <li role="presentation"><a href="../../create/">New Post</a></li>
          <li role="presentation"><a href="#">About</a></li>
        </ul>
      </nav>
      <h3 class="text-muted">Guestbook</h3>
    </div>
      <div class="jumbotron">
          <h2>{{ question.title_text }}</h2>
          <p>{{ question.question_text }}</p>
      </div>
</div>
<nav class="container">
  <ul class="pager">
    <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
    <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
  </ul>
</nav>

</body>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>